### ISSUE TITLE
Buddies with event bonus do not function

### ISSUE THREAD

**Issue by SuperAj3** [RunnersRevival/revival_issues#1]
The additional bonus provided by using the "Catridge" buddy during the Anniversary event does not apply to the total cake collected at the end of a run.

**Comment by F121Live** [comment]
Updating on this:

This happens to all of the buddies that affect event scoring.

Still investigating this issue.

**Comment by F121Live** [comment]
Fixed in 2.2.1.

**Comment by F121Live** [comment]
Reopening, even though it's solved, the fix has yet to be released.
Will close when 2.2.1 is out.
