### ISSUE TITLE
Server migration issues.

### ISSUE THREAD

**Issue by Val-Arts** [RunnersRevival/revival_issues#107]
**Describe the bug**
Upon the server maintenance ending I've opened up Sonic runners revival and can't connect to the server. I have used the 1.1.1.1 and WARP as recommended with the same results.

**To Reproduce**
1. Open Runners revivall
2. Encounter no connection to server
3. Close revival and open up 1.1.1.1 and enable DNS
4. Boot up Revival
5. Encounter same issue as step 2
6. Repeat Step 3 and 4 with WARP.

**Expected behavior**
I'm not sure what'd you expect, but for my Galaxy A23, I have not been able to open Revival at all..

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Device specifications (please fill out the following information):**
 - Device: Galaxy A23
 - OS: Android 13
 - Game Version: 2.2.4

**Additional context**

**Comment by JKouga** [comment]
You will need to go to your phone settings to make the change happen.  If you're on Android, you go to your phone settings -> connections -> More connection settings -> Private DNS.  Once you are at Private DNS, you then change the option to "Private DNS provider hostname" and then you type in `1dot1dot1dot1.cloudflare-dns.com`.  You'll need to give it at least a few hours for the changes to happen.  You can then try again after you wait.

**Comment by Val-Arts** [comment]
Hi there, I've waited a few hours as mentioned and went to play, I'm still experiencing the same issues with the steps you provided. no results have changed and it still remains unplayable

**Comment by JKouga** [comment]
Let's try something a bit different.  Try to open the following URL on your phone's browser:

https://game.sonicrunners.com
https://assets.sonicrunners.com

For the game URL, it should give you an "OK" text after loading it.  For the Assets URL, it should give you the "Assets" text after loading it.  If you see those text, it means that you connected to them successfully.  If not, then I will forward this issue to one of the dev team members.

**Comment by JKouga** [comment]
Going to give an update on this issue.   Our dev team is investigating the problem.  We'll let you know if we are able to find the cause of the problem and potential solutions to the problem.

**Comment by JKouga** [comment]
We have resolved the issue.  The connection issue is caused by the corruption of the game's client.  We also found out that the iPhone version was also missing their corresponding download files and the non-HD assets.  We are also able to fix this.  In order to fix the connection issue, our dev team needs to migrate your account over to a new one.  If you haven't already, please contact either \_F121\_  or FairPlay137 on discord with the following details:

* Current ID (or Username)
* Newly generated ID (You'll have to delete your data in the app settings)

We sincerely apologize for the inconvenience.

**Comment by Val-Arts** [comment]
Hi there.

I got contacted by _F121_ already via discord about the situation and was assisted with migration to a new save.

Thank you though for telling me however. I appreciate the support that has been provided to me

**Comment by JKouga** [comment]
Alright, then we can call this issue resolved.
