### ISSUE TITLE
Game Crashes when attempting to start run

### ISSUE THREAD

**Issue by TheYearIsTwentyGX** [RunnersRevival/revival_issues#113]
**Description:**
I'm able to get to the title screen, and was able to play the tutorial level. I was able to get through all of the news, register my name, go through a game update, and view the main menu. However, attempting to choose either Story Mode or Timed Mode shows a static image on the loading screen (As in, it goes to the loading screen, but the loading animation is frozen). It will stay on this screen, unmoving, until you tap the screen. When you tap, it crashes the game.

**To Reproduce**
1. Open the app.
2. Tap the screen when presented with "Touch the Screen"
3. Press either of the "PLAY!" buttons
4. Observe the frozen loading screen
5. Tap the screen to crash the game

**Device Specs:**
 - Device: Samsung Galaxy S24 Ultra
 - OS: Android 14, One UI version 6.1
 - Game Version: 2.3.0 Public Beta 2

**Additional Context:**
Following the tutorial, I did receive an error during the primary game asset download (at 80%). Restarting the game did finish downloading the remaining assets, however.

**Comment by JKouga** [comment]
The dev team is aware of the issue.  Did it look something like this:

https://github.com/user-attachments/assets/986251a3-c2ca-484d-b2a3-d11f29a622aa

**Comment by TheYearIsTwentyGX** [comment]
So I went to record what was happening, as it was actually something unlike what you attached. But when I went to record, the game began working as expected, lol. Guess we can close this issue 🤷
