### ISSUE TITLE
Unable to access Event banner during Story Mode or main menu

### ISSUE THREAD

**Issue by Val-Arts** [RunnersRevival/revival_issues#12]
**Describe the bug**
When trying to open the event at all, it shows a connection error and then goes blank (I've attempted to clear cache and have still received the same result) 

**To Reproduce**
1. Open up Runners Revival.
2. Click on Event Banner on Story Mode (the other problem has been mentioned here)
3. wait for it to load.
4. shows connection error, cleared cache on my device and still received the same issue

**Expected behavior**
When I clicked the Event Banner, it was meant to take me to the event page, it however stuck me on a loading screen and then an error screen with no results at all.

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: P609 (Optus X Wave)
 - OS: Android 9
 - Version: 2.2.0

**Additional context**
I have attempted to clear cache four times before writing my report. it all resulted the same way as mentioned above

**Comment by FairPlay137** [comment]
Are you using the "t" version or the "non-t" version?

**Comment by F121Live** [comment]
This is either a cache corruption on your end or a slow download time, please try refreshing your cache by clicking on the "clear cache" button in the title screen.
I couldn't replicate this issue on any of my devices.
