### ISSUE TITLE
The Korean version of the game's texts are in Japanese + Some modes don't load

### ISSUE THREAD

**Issue by Sean1220** [RunnersRevival/revival_issues#13]
**Describe the bug**
Most of the texts in the game are in Japanese. Also, the Story mode, Roulette, Character Page, and the Buddy Page does not load.
(Tested with before and after clearing the cache)

**To Reproduce**
1. Open up Sonic Runners Revival.
2. Click on Story mode, both Roulettes, Character Selection Page, or the Buddy Selection Page.
3. Does not load.
4. Story - Black Screen
Roulettes - Does not load
Character Selection Page - Only shows the first four characters(Sonic, Tails, Knuckles, and Amy) and other buttons does not load
Buddy Selection Page - Does not load
The Rest of the in-game Text - Mostly in Japanese or does not load at all

**Expected behavior**
Story mode goes dark and does not load.
Both Roulettes do not load and can't be activated.
Character Selection Page only shows the first four characters and every other buttons other than swapping characters, limit break, and level-up buttons.
Buddy Selection Page does not load at all(Both Characters and buddies can be swapped in the Item Select Menu).
Most of the Korean texts are in Japanese.

**Screenshots or videos**
https://drive.google.com/file/d/1ssxtBILnOE1r0TU5JGnPmWHIsDfaGIhq/view?usp=sharing
A Google Drive Link for the video showcasing problems. Tested and recorded with Bluestack.

**Smartphone (please complete the following information):**
 - Device: Galaxy S21 5G, Bluestack 5
 - OS: Android 12
 - Version: 2.2.0

EDIT: Changed the link for the video since I had the edited version, but forgot to link it.

**Comment by FairPlay137** [comment]
Is this happening after clearing the cache from the title screen? We've recently updated our Korean text translations, and we'd like to know if these issues are happening even after a full cache clear.

**Comment by Sean1220** [comment]
The cache is cleared with both devices. I am the Korean translator for SR, and I do not know how this happened. Also, the event story did not get updated to a newer version that I made.

**Comment by F121Live** [comment]
Solved.
