### ISSUE TITLE
Data Transfer and Wifi Connection when the connection is working

### ISSUE THREAD

**Issue by stkproduction11** [RunnersRevival/revival_issues#14]
When I try to link my account to a different phone (or Bluestacks) it doesn't work -_-

**Comment by stkproduction11** [comment]
and by the way, I entered my ID and password correctly

**Comment by JKouga** [comment]
In order for you to transfer your save, you will need to be able to back up your sfrn.game and ifrn.game files from Revival.  Also,  stk, for next time and beyond, please make sure you follow the report template in order to report bugs.

**Comment by FairPlay137** [comment]
Should no longer be an issue as of February 2023
