### ISSUE TITLE
In Offline Mode, Character Controls Photo Is Broken

### ISSUE THREAD

**Issue by ItsTerly** [RunnersRevival/revival_issues#15]
**Describe the bug**
When you never tried any of offline mode characters before, (Sonic, Tails, Knux) when you try offline mode, you will see Controls introduction card. But in offline mode, their controls introductions photo is only a white rectangle.

**To Reproduce**
0. Make sure about you never played with any of offline mode characters. (Sonic, Tails, Knuckles)
1. Open up Runners Revival.
2. Click on Offline mode.
3. Choose the character that i mentioned about in step zero.
4. Click on play button.
5. Wait until game starts.
6. Be enjoy with your bug.

**Expected behavior**
It's actually need to work like this controls introduction card:

![Screenshot_20220701_135341_com sonicrunners revival](https://user-images.githubusercontent.com/108524952/176888222-f69c1fe1-3a19-4f54-bbbe-dc1ad373fe9a.jpg)

But photo is buggy.

**Screenshots or videos**
Bug:

![Screenshot_20220630_215931_com sonicrunners revival](https://user-images.githubusercontent.com/108524952/176887431-a50509be-34ca-4070-ac95-7489afd7e40a.jpg)

**Smartphone (please complete the following information):**
 - Device: [Huawei P30 Lite]
 - OS: [Android 10]
 - Version: [2.2.0]

**Additional context**
Also, if you enter to offline mode and finish a game, you will see this:

![Screenshot_20220630_220434_com sonicrunners revival](https://user-images.githubusercontent.com/108524952/176887980-43252792-3eda-40bf-8d37-2f502a8e28a4.jpg)

It can be fix.

**Comment by JKouga** [comment]
The behaviors should be expected.  The tutorial textures were not added for offline mode.  As for the characters not showing up for EXP calculation, you should expect that behavior as well since playing in an offline mode run will not save your progress.

**Comment by ItsTerly** [comment]
We can't get rid of them in offline mode?

**Comment by ItsTerly** [comment]
Oops, i accidently closed..

**Comment by F121Live** [comment]
This is a design choice.

**Comment by FairPlay137** [comment]
We tried skipping the experience window, but we decided against it for the final 2.2.0 release as a design choice. (There is a currently unused animation which was used back in the 1.0.x days back when the XP display wasn't shown after a run, but we haven't been able to get it working)
