### ISSUE TITLE
The Korean version of the game does not load the Story Mode

### ISSUE THREAD

**Issue by Sean1220** [RunnersRevival/revival_issues#17]
**Describe the bug**
The Story Mode would not load after the screen goes dark.
(Tested with before and after clearing cache)

**To Reproduce**
1. Go to the Story Mode.
2. Press Play.
3. Screen goes dark and does not load the game.

**Expected behavior**
Cannot play the story mode. Everything else works fine with the re-translated text.

**Screenshots or videos**
-

**Smartphone (please complete the following information):**
 - Device: Bluestacks 5
 - OS: Android, 5.7.110.1002 N32
 - Version: 2.2.0

**Additional context**
PLEASE NOTE!

I tried it with Bluestacks that has no story progressed.
However, my phone(Galaxy S21 5G) that completed the campaign and re-doing the last story chapter ran the Stroy Mode no problem. It even loaded the new text fine.
I am not sure if the cause is the device, the progress of the story that could not load the some portion of the story files for some reason, or both.

**Comment by F121Live** [comment]
Could this be related to wrong text formatting within the new translation?

**Comment by Sean1220** [comment]
If that is the case again, I am terribly sorry.

**Comment by F121Live** [comment]
Solved in 2.2.1B.
