### ISSUE TITLE
Typical resource download problem

### ISSUE THREAD

**Issue by EmmaCoded** [RunnersRevival/revival_issues#18]
**Describe the bug**
Every time I try to download the resources, almost at the end it gives an error, with Vpn there are sometimes more chances that it will work, but then you have to update everything and everything is lost, mostly Everything fails when it reaches 180/210

**To Reproduce**
1. Go to "You just touch the home screen"
2. Ask for resource download, duh
3. Download up to 180/210, and it says connection loss, if you hit retry, 5 minutes go by without anything being downloaded, and it says connection loss again

**Expected behavior**
"Let it be downloaded 😎👌"

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.
![Screenshot_2022-07-05-14-48-03-470_com sonicrunners revival](https://user-images.githubusercontent.com/108761396/177400759-440c83fc-7580-405d-af5c-2af7189f1b44.jpg)

**Smartphone (please complete the following information):**
 - Device: [Redmi 9A - Siragon 5250]
 - OS: [Android 10 Q MIUI V11 (Android 10) - Android 8.1.0]
 - Version: [android 10 - android 8.1.0]

**Additional context**
Te la comes con Pretexto 
![f6681b1dae4130164c32dfe50d5c7841](https://user-images.githubusercontent.com/108761396/177401406-40d7762f-ad64-4f41-87c4-cb149520d316.gif)

**Comment by F121Live** [comment]
Not something we have control of.
