### ISSUE TITLE
sonic is stuck on the wall when i do the double jump

### ISSUE THREAD

**Issue by SonicIsTheBest2022** [RunnersRevival/revival_issues#20]
I was playing quiet when I did the double jump to try to save myself from the fall and when I did the double jump sonic got stuck in the wall

The Version Game is the last update
My Cellphone is a Samsung Galaxy A10
My OS is the android 12
Here is a evidence
![Screenshot_20220730-004734_Sonic Runners Revival](https://user-images.githubusercontent.com/110273363/181871738-7c59ed97-9c9a-43b2-84a4-48156bf044cf.jpg)

**Comment by FairPlay137** [comment]
This is an issue that happens with the original game. We aren't quite sure what causes the characters to clip into the wall, but rest assured we are aware of it.

**Comment by TheMasterOfMike** [comment]
> This is an issue that happens with the original game as well. We aren't quite sure what causes the characters to clip into the wall, but rest assured we are aware of it.

iirc it was said a while back that the game only checks for collision on active frames. Given that the game probably will have at least one dropped frame sometimes (which is especially likely given that the Galaxy A10 is an extremely extremely old _budget_ Android phone)

**Comment by BlueStarWB** [comment]
while it sometimes doesn't work, (when playing solo it's just rotten luck. sorry to hear people having the issue.) I've found that sometimes if you Switch character while clipped against the wall, it'll bump yourself out of the wall and you can keep going.
