### ISSUE TITLE
Music not playing properly after unmute

### ISSUE THREAD

**Issue by DeadCell33** [RunnersRevival/revival_issues#28]
**Describe the bug**
If the music is off in the menu and then a stage is started and you turn the music back on the music won't play until either a wisp or invisibility power up is grabbed.

**To Reproduce**
1. Have the music slider turned all the way down on the main menu
2. Start a run
3. Pause and turn the music back on from the sound setting

**Expected behavior**
Music won't play until a power up with unique music plays its song and then the normal stage music will play.

- Version: 2.2.2

**Comment by Ramen2X** [comment]
This issue has been addressed internally and is waiting for public release.

**Comment by Ramen2X** [comment]
Fixed in 2.2.3.
