### ISSUE TITLE
Tangle and Whisper's Bonuses don't appear correctly

### ISSUE THREAD

**Issue by SuperAj3** [RunnersRevival/revival_issues#30]
The Score Bonus, Ring Bonus, Animal Bonus, Distance Bonus and Enemy bonus do not display the correct values if Whisper or Tangle is selected as one of your characters.

**To Reproduce**
1. Go to 'Your Characters' OR click on the "Team Confirmation" screen
2. Click on Tangle or Whisper as either your main or sub-character / scroll through the characters until one is Tangle or Whisper.
3. click on the "Buddies" button in the bottom corner
4. If changing character on the "Team Confirmation" screen bonus values will not change when you switch to Tangle or Whisper. If you pick both characters in the "Your Characters" screen, when you view the "Team Confirmation Screen", the bonus values all display as "+000%",

**Expected behavior**

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/71704997/191950807-dc6a8041-95e0-444e-aed9-d9fb5fd2c47c.png)
![image](https://user-images.githubusercontent.com/71704997/191950840-defe5b2d-fa02-4b2e-aa4e-3cd987d46610.png)
If selecting characters THEN viewing the "Team Confirmation" screen:
![image](https://user-images.githubusercontent.com/71704997/191950875-ba89ab2b-8a2f-4bbd-844f-8f279f808d3d.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Flip 3
 - OS: Andoid 12
 - Version: 2.2.2
 
**Additional context**
Possibly also happens with Marine's stats as well.

**Comment by JKouga** [comment]
Commenting further on the bug, if you only equip Tangle or Whisper as your main or sub character, only their base stats (their 50% Score Bonus applies).  Equipping Tangle and/Whisper to your character team does not use their current stats.

**Comment by JKouga** [comment]
Can also confirm that this also happens when you also equip Marine as well.  I definitely do think we need to look at what is going on with the newly added characters.

**Comment by F121Live** [comment]
*Whyyyyy?*


Will look into this...

**Comment by Ramen2X** [comment]
This issue has been addressed internally and is waiting for public release.

**Comment by Ramen2X** [comment]
Fixed in 2.2.3.
