### ISSUE TITLE
Flickering of Main Menu Hub while in Buddy Loading Screen after a Story Mode/Timed Mode Run

### ISSUE THREAD

**Issue by JKouga** [RunnersRevival/revival_issues#31]
**Describe the bug**
While in the loading screen after passing through the results screen or hitting return to the main menu, the flickering of the main menu hub will appear briefly, and the top of the main menu bar will appear.

**To Reproduce**
1. Finish a Story Mode or Timed Mode Run
2. Click on Next after getting to the Results Screen OR Pause and Return to Main Menu
3. Takes you to the loading screen
4. While in the Loading Screen, the top of the menu bar will pop up and the main menu screen will flicker briefly

**Expected behavior**
The loading screen should just show the buddy and that's it.  No flickering or any other unexpected behavior

**Screenshots or videos**

**Smartphone (please complete the following information):**
 - Device: Xiaomi K50 Gaming
 - OS: Android 12
 - Version: 2.2.2

**Additional context**

**Comment by F121Live** [comment]
Related to #32 .

**Comment by F121Live** [comment]
This was fixed internally.
