### ISSUE TITLE
Supposedly missing assets

### ISSUE THREAD

**Issue by DrIvoRobotnik1991** [RunnersRevival/revival_issues#32]
While playing over my cellular data, some assets on menus seemed to be missing whenever I boot up the game

![Screenshot_20220925-151335](https://user-images.githubusercontent.com/114360700/192161424-a87a8aff-8cdc-463a-97d2-0a653d129203.png)
![Screenshot_20220925-151329](https://user-images.githubusercontent.com/114360700/192161426-a1feab25-80b0-40e8-b953-d37ea8e4a12e.png)

Device: Google Pixel 6a
Version: Android 13

I'm sorry if my report in incomplete. This is my first time doing this

**Comment by F121Live** [comment]
This was fixed internally.
