### ISSUE TITLE
Background on preparations screen are white and stage type always displays as speed stage untill you return to main menu after playing story mode during Animal Rescue event

### ISSUE THREAD

**Issue by Ceotom** [RunnersRevival/revival_issues#33]
**Describe the bug**
Background on preparations screen are white and stage type always displays as speed stage, even when it's not, untill you return to main menu after playing story mode during Animal Rescue event.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start story mode run (Don't matter, from main menu directly or from map)
2. Finish or abandon the run 
3. Without leaving map press play button
4. You should notice that someone stole background 

**Expected behaviour**
Background and current stage should display correctly, depends from current stage

**Screenshots or videos**
https://youtu.be/oY06Pyk-2Qc?t=56 (Cant embed video directly, GitHub app sucks)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A1
 - OS: Android 11
 - Version: 2.2.2

**Additional context**
This don't occurs if you play time attack.
Unsure if this error occurs before chapters that have random stage.

**Comment by Ramen2X** [comment]
This issue has been addressed internally and is waiting for public release.

**Comment by Ramen2X** [comment]
Fixed in 2.2.3.
