### ISSUE TITLE
Graphics cover the Total Score amount in Story Mode runs

### ISSUE THREAD

**Issue by GrandMac1999** [RunnersRevival/revival_issues#34]
**Describe the bug**
What I believe to be a layer from the background covers up

**To Reproduce**
1. Play and finish a Story Mode run
2. Finish the run
3. See error

**Expected behavior**
Total Score should be clearly visible and not covered up by anything

**Screenshots or videos**
![3A0AA78E-0A00-46FC-B5E9-F81E316DFF85](https://user-images.githubusercontent.com/104725054/192270915-277e5bc0-1cf8-4602-a811-2d9f89e146e8.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.6.1
 - Version: 2.2.2t

**Additional context**
N/A

**Comment by F121Live** [comment]
Not the real issue, this happens when UI assets haven't been loaded correctly due to a corrupted download, clear cache.
