### ISSUE TITLE
Premium Roulette isn't giving new rewards

### ISSUE THREAD

**Issue by BlueStarWB** [RunnersRevival/revival_issues#37]
maybe it's just because I have most of the basic buddies (non-event) maxed out to Lv.10 but... the Premium Roulette is only giving duplicate results now, occasionally Tangle or Whisper or some other duplicate character I already have and when I use the Special Eggs (which, I assume is supposed to be guarantee a new buddy or character you don't have maxed out yet but it doesn't sound right since I am getting duplicates from Special Roulette consistently) it can result in a duplicate with more special eggs.

I like the roulette and all (I'll post my buddies and characters) but if it just hits a brick wall with no new results there isn't much point to it, I'm even getting Mother Wisp (event buddy) from SE Roulette when I know I'm not supposed to be.
![Screenshot_20220929-160800_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192958854-630baa4a-7335-482d-8c70-c6d92a5a9e35.jpg)
![Screenshot_20220929-160810_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192958864-fccd433d-437a-45d6-b0ee-5a776513bb64.jpg)
![Screenshot_20220929-160820_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192958869-000c261b-f13d-4da6-bfe6-eb4dd7d6485b.jpg)
![Screenshot_20220929-160833_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192958875-ce3ac5a2-82fe-4d0e-aa97-5458bd194c2d.jpg)
![Screenshot_20220929-160845_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192958877-15fced10-9704-4234-a91f-de2e07365429.jpg)
![Screenshot_20220929-163440_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192958879-8b494134-6cf6-494b-adf6-8d109bf514d8.jpg)
![Screenshot_20220929-163457_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192958883-b0402cec-4255-46bb-b1d3-a4ffe81d3243.jpg)
![Screenshot_20220929-163508_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192958888-af978195-d899-46b3-a6ae-95b129f9f1c0.jpg)
![Screenshot_20220929-163520_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192958892-2b9eb471-8fb2-4bbf-9f83-c0757a78abcf.jpg)
![Screenshot_20220929-161850_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192959289-be84dfbc-6b1e-4c35-b965-86287547fe23.jpg)
![Screenshot_20220929-161803_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192959298-71bf0005-875c-4f95-a4ae-abd05c260533.jpg)
![Screenshot_20220929-161806_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192959302-f63a2f56-9e98-4510-9d3c-56448908d59a.jpg)
![Screenshot_20220929-161817_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192959307-be5be70c-66ab-4e23-af17-a1c79fdc6e15.jpg)
![Screenshot_20220929-161822_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192959309-2d47cb18-5215-4840-88b0-60324ffa4d16.jpg)
![Screenshot_20220929-161827_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192959315-fe356554-77bb-46f5-9c4f-4a75781a86ab.jpg)
![Screenshot_20220929-161835_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192959318-e2935503-9ba3-4761-b44b-5ff675b309f6.jpg)
![Screenshot_20220929-161840_Sonic Runners Revival](https://user-images.githubusercontent.com/77420948/192959321-fcd6b74e-1fe7-4d60-9da6-925f2dd927d8.jpg)

I guess my point is: the Premium and Special Egg Roulettes are barely giving anything "New" it's just spitting out duplicates and wasting Red Star Rings. I get maybe One new thing every 2nd 5 spin I can do and that's it, maybe it's just rotten luck,
but I thought I'd bring it to attention anyway just in case something was wrong.

**Comment by F121Live** [comment]
Not an issue.
