### ISSUE TITLE
Pixel 7, Pixel 7 Pro, Android 14, and The State of 32-Bit App Support

### ISSUE THREAD

**Issue by TheMasterOfMike** [RunnersRevival/revival_issues#38]
(Ditching the format of the bug report because imo it's somewhat out of scope given the circumstances)

## Pixel 7 and Pixel 7 Pro

With the release of the Pixel 7 and Pixel 7 Pro, Google has decided to implement something that has been worked on since Android 12 but is actually "stable" now with Android 13.

That thing is **64-bit only Android ABI's** - What this means (in case you are wondering) is that **32-bit app support is completely gone**, which impacts many older apps, **including Sonic Runners Revival**

Given this, plus the next point, it is also probably safe to assume that newer midrange to top end Android devices will likely start going with this approach as well as time passes

## Android 14

But the impact is not just limited to new devices (in the long term) - based on _unfinalized_ documents, Android 14 could very likely **drop 32-bit app support for devices using an armv9 SoC** (e.g. the Snapdragon 8 Gen 1, used in devices like the Samsung Galaxy S22)

## The State of 32-Bit App Support

_(Disclaimer: I am not an Android dev, I do not know much about Android dev stuff, I could be wrong with some of the below)_

These changes will cause an immense amount of issues over time - Sonic Runners Revival will need to become a 64-bit app, which will add some development time and could potentially result in an indeterminate amount of delays to other things that end users may desire (such as Bug Fixes, Events, and more)

Assuming that Google won't change more is a terrible idea - the Pixel 7 and Pixel 7 Pro have already executed this change, the rumored Pixel Tablet is set to also have this same change. Besides, 32-bit only apps have not been allowed to be released onto the Play Store since August 2019 - over 3 years ago

Q: "But can't we do this wholesale and ignore having to worry about 32-bit and 64-bit together"
A: Problem with that ends up being that - for some weird reason - Google forces lower-end/budget devices to use 32-bit only Android, which ends up meaning that killing 32-bit altogether will kill the ability for budget device owners to be able to run Sonic Runners Revival

This is a critical issue - and one that could potentially cause significant delays or significant headaches to more things and more users as time goes on.

**Comment by FairPlay137** [comment]
Google's official documentation says the best way to migrate Unity Android apps to using 64-bit is by upgrading the project to Unity 2017.4.16 or later. Since that may take a while, we're going to look for alternative ways we could get 64-bit versions of Revival running on Android. The iOS version is already 64-bit due to the version of Xcode we're using doing that by default, so in theory it may be possible to use a workaround to create a 64-bit version of the APK.

**Comment by TheMasterOfMike** [comment]
> Google's official documentation says the best way to migrate Unity Android apps to using 64-bit is by upgrading the project to Unity 2017.4.16 or later. Since that may take a while, we're going to look for alternative ways we could get 64-bit versions of Revival running on Android. The iOS version is already 64-bit due to the version of Xcode we're using doing that by default, so in theory it may be possible to use a workaround to create a 64-bit version of the APK.

Keep in mind that Sega actually had to build Sonic Runners for 64-bit on iOS in the first place, due to a requirement put in place in Apple starting on February 1st, 2015 that all newly released apps needed to use the iOS 8 SDK and support 64-bit - there's a Unity article here which went into it https://blog.unity.com/technology/apple-ios-64-bit-support-in-unity

**Comment by FairPlay137** [comment]
With 2.3.0 Public Beta 1 out now, being a jump from Unity 4.7.2 to Unity 2019.1.14, this issue can be safely closed.
