### ISSUE TITLE
My Username is Flagged as Inappropriate ``Zer0Necrosis``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [RunnersRevival/revival_issues#40]
Since this is just about the game flagging my username is inappropriate other info besides the app version is not needed.

App version: srr222.apk acquired here. https://sonicrunners.com/#/download

I use this tag on Nintendo servers so I know its not offense also my name means ``NotDead``

Z e r +number0 N e c r o s i s = Zer0Necrosis

You can pretty much google me as I have been around the block.

Let me know if you want me to test something.

**Comment by Ramen2X** [comment]
Can you provide your ID if possible? (Ten digit number found in the top-left corner of the title screen)

**Comment by P3rf3ctXZer0** [comment]
yeah let me boot up.

**Comment by Ramen2X** [comment]
I have manually corrected your username for the time being as we look into this.

**Comment by P3rf3ctXZer0** [comment]
Okay I will log in as that thank you.

**Comment by P3rf3ctXZer0** [comment]
I see you actually made it my user name thank you :D
