### ISSUE TITLE
iPadOS 16.1 bug

### ISSUE THREAD

**Issue by Andy4169** [RunnersRevival/revival_issues#41]
**Describe the bug**

**To Reproduce**
1. Get Sideloadly ipa file and install it on iPadOS 16.1
2. Click on 'Revival'/the name of the game you installed it as on the home menu
3. See error

**Expected behavior**
App on iPadOS working fine on 16.1

**Screenshots or videos**
![IMG_0118 1](https://user-images.githubusercontent.com/108393910/197368721-972f253b-ef07-419f-96bd-26ec838a3da8.PNG)
![IMG_0119 1](https://user-images.githubusercontent.com/108393910/197368757-4fc86cb6-c6e9-40ca-936c-5a423c2f3a0b.PNG)

**Smartphone (please complete the following information):**
 - Device: iPad 6th gen
 - OS: iPadOS 16.1
 - Version: 2.2.3/2.2.2

**Additional context**
iPadOS says it doesn't support the current version

**Comment by TheMasterOfMike** [comment]
Are you trying to use the jailbroken option by chance? If so that's not gonna work.

You need to follow https://sonicrunners.com/#/sideloadly

**Comment by Ramen2X** [comment]
In the future, please correctly follow our bug report template and provide step-by-step information on how to reproduce the issue. Otherwise, we cannot guarantee that we can help you.

**Comment by Andy4169** [comment]
> Are you trying to use the jailbroken option by chance? If so that's not gonna work.
> 
> You need to follow https://sonicrunners.com/#/sideloadly

no im not and i already did

**Comment by Andy4169** [comment]
> In the future, please correctly follow our bug report template and provide step-by-step information on how to reproduce the issue. Otherwise, we cannot guarantee that we can help you.

fixed

**Comment by TheMasterOfMike** [comment]
Sorry for the late response. Does Sideloadly give any errors at all or no?

**Comment by Andy4169** [comment]
> Sorry for the late response. Does Sideloadly give any errors at all or no?

no

**Comment by TheMasterOfMike** [comment]
Hmm, time to do the "let's try something random and hope it works" strategy

I guess what you can try doing is following https://sonicrunners.com/#/altstore - it's a no longer officially supported method but the tool is still technically maintained.

Alternatively, you can restore to 15.7 (16.1 isn't released, it's only a release candidate, though it also releases tomorrow so)

**Comment by F121Live** [comment]
You are not following the installation guide correctly, please read the guide in our website.
