### ISSUE TITLE
Game crashes after completing a offline mode run

### ISSUE THREAD

**Issue by RealPogger** [RunnersRevival/revival_issues#42]
**Describe the bug**
When you complete a run, the game crashes in offline mode

**To Reproduce**
1. Go to Offline Mode
2. Click on any stage in offline mode
3. Complete the run of offline mode
4. Game crashes

**Expected behavior**
After the offline run is complete, it will take you back to the offline stage selection screen.

**Screenshots or videos**
https://user-images.githubusercontent.com/92672257/197397216-2d9bb2ce-f5e9-4511-8fdc-fc11f447dc14.mp4

**Smartphone (please complete the following information):**
 - Device: Fire HD 8 Plus
 - OS: Android 9 Pie
 - Version: 2.2.3/2.2.2

**Additional context**
This problem also happens when you have a internet connection

**Comment by F121Live** [comment]
I can't seem to be able to reproduce this.
Sorry.
