### ISSUE TITLE
Special Music will not play after the first play of a session

### ISSUE THREAD

**Issue by TheMasterOfMike** [RunnersRevival/revival_issues#44]
**Describe the bug**
In the Halloween Event, after doing the first run of it and either failing or quitting it, re-entering will cause special music to not play.

**To Reproduce**
1. Start a run
2. Finish or quit that run
3. Start another run
4. No special music plays (invincibility and similar do though)

**Expected behavior**
Special Music should play (under normal conditions) regardless of circumstances.

**Screenshots or videos**
_man I love when GitHub won’t let me upload a file bigger than 10 MB_

**Smartphone (please complete the following information):**
 - Device: iPad Air 4th Generation
 - OS: iPadOS 15.4
 - Version: Ver. 2.2.3t

**Comment by sayoai** [comment]
I can confirm this is true! I’m also playing the game on an iPad Air gen 4 and this does happen. The bug does seem to fix itself when you start another run but I’m pretty sure the run after that also has no music.

**Comment by Ramen2X** [comment]
Very perplexing issue that didn't come up in testing... can confirm it's 100% reproducible on my end though. Will be looking into this.

**Comment by Ramen2X** [comment]
This was a server-side issue that should be resolved now.
