### ISSUE TITLE
The problem of disappearing texts（Language:Chinese）（Halloween Event）

### ISSUE THREAD

**Issue by MaoChonLonper** [RunnersRevival/revival_issues#45]
**Describe the bug**
I can't change the language setting, so I only can playing with Chinese.
But texts are unable to display, can you help?

**To Reproduce**
1. Go to Halloween Special Stage
2. See error. Every story or dialogues texts are blank.

**Expected behavior**
Showing some texts that now I can't see??

**Screenshots or videos**
![Screenshot_20221024-144034_Sonic Runners Revival](https://user-images.githubusercontent.com/116544364/197467723-8ff004c0-5987-43ab-a299-237ae0afac9a.png)
![Screenshot_20221024-154104_Sonic Runners Revival](https://user-images.githubusercontent.com/116544364/197473314-1d9d28a2-97a7-4179-8a7a-8e7a7d0ae838.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Tab S7+ 5G
 - Android 12
 - Version: 2.2.3t

**Additional context**
Please add "Change Language" options, I understand you guys can't solve the problem about Chinese.
Actually, I want to using English interface, please.

And sorry for my broken English ><

**Comment by F121Live** [comment]
Interesting, none of the Chinese versions got an official translation for this event.
Looks like SEGA either forgot or didn't plan on running this event in China (We know that they had some sort of regional events system)

Sorry for the inconvenience, in order for us to fix this, we would need to translate the original story to Traditional Chinese and Simplified Chinese.
Unfortunately we don't have any Chinese translators.
For the next time we run this event, we will most likely be putting the original English text in there.

![imagen](https://user-images.githubusercontent.com/55333985/210153652-c2af1ffe-cef8-465a-aea8-ad464044a477.png)
![imagen](https://user-images.githubusercontent.com/55333985/210153660-b609e123-b4c0-4b98-b222-faec1062b629.png)
