### ISSUE TITLE
Character doesn’t rank up after multiple copies

### ISSUE THREAD

**Issue by Lau0177** [RunnersRevival/revival_issues#47]
**Describe the bug**
During Story mode grind , after I had already purchased tails I obtained a second copy via eggs and the rank was unchanged 
**To Reproduce**

**Expected behavior**
Character rank up
**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone X]
 - android Samsung galaxy note 9
 - OS: [e.g. iOS 14]
 - Version: [e.g. 2.2.0]
Latest
**Additional context**

**Comment by F121Live** [comment]
Story Mode only *unlocks* characters.
This is intended behaviour.
