### ISSUE TITLE
Brazilian version of the holiday event has no text

### ISSUE THREAD

**Issue by Glamurina** [RunnersRevival/revival_issues#48]
**Issue Description**
All dialogue in the brazilian portuguese version of the holiday event is absent, all that appears in its place is "NoText".

**To Reproduce**
Simply open the event in portuguese

**Screenshots or videos**
![Screenshot_20221224-084659](https://user-images.githubusercontent.com/121343039/209435299-66ad2a97-6e2c-41ce-8e53-41a1dc2aa9a2.png)

**Smartphone (please complete the following information):**
 - Device: moto g(8) plus
 - OS: Android 10
 - Version: 2.2.3

**Comment by F121Live** [comment]
Fixed in 2.2.3D
