### ISSUE TITLE
Christmas NiGHTS BGM not playing after first play of a session

### ISSUE THREAD

**Issue by MorganM97** [RunnersRevival/revival_issues#49]
**Describe the bug**
After doing the first run with Christmas NIGHTS as a first buddy & BGM music on, and either failing or quitting it, doing another run will cause the BGM music to not play.

**To Reproduce**
1. Have Christmas NiGHTS as your first buddy
2. Make sure the BGM music is set to on
3. Start a run
4. Finish or quit that run
5. Start another run and make sure the BGM music is set to on
6. No Christmas NiGHTS BGM music plays

**Expected behavior**
Christmas NiGHTS' BGM music should play (under normal conditions) when it's set to on.

**Screenshots or videos**
Unfortunately, the video is over 10MB, which Github won't let me upload.

**Smartphone:**
 - Device: iPhone XR
 - OS: iOS 16.2
 - Version: Ver. 2.2.3

**Comment by F121Live** [comment]
Thanks for reporting, I'll look into this.

**Comment by F121Live** [comment]
Update: Apparently the flag gets inverted LOL, that's interesting.

You should be able to hear the background music again by "disabling" (removing the tick) the bgm button.

**Comment by MorganM97** [comment]
Huh, weird. I was able to disable the BGM button during the second run, and I heard the Christmas NiGHTS BGM playing. It happened that way as well, when the buddy BGM is supposed to be played when the BGM is enabled.

I even tried that with Opa-Opa, and the same result happened as well, so I guess it relates to any buddy that has its exclusive BGM (Not sure if same happens with the other Fantasy Zone buddies, considering I don't have them. And the NiGHTS event has yet to be run to know if the buddies' BGM has the same result)

**Comment by F121Live** [comment]
I was the one who originally added this feature and I can tell, yep, it acts the same for every buddy that has bgm attached to it.

The flag getting inverted is an oversight from me, I should be checking the activation status before entering the item set menu, we are not doing that at all.

**Comment by F121Live** [comment]
Fixed in the upcoming 2.2.4 patch.
I will close this issue when the update goes live.

**Comment by MorganM97** [comment]
Thank you very much. Looking forward to the patch when it comes out

**Comment by Abrahamelxd2021** [comment]
![Screenshot_20230210-173058](https://user-images.githubusercontent.com/104541078/218215869-a77664c5-545a-45e2-b2d1-8885f9de80fd.png)

**Comment by FairPlay137** [comment]
A fix has been included in 2.3.0 Public Beta 1.
