### ISSUE TITLE
Music sets to 0% after opening Sound Settings first time during run

### ISSUE THREAD

**Issue by Ceotom** [RunnersRevival/revival_issues#5]
**Describe the bug**
If you first time open Sound Settings during run music will be set to 0%.
This does not happen with sound.

**To Reproduce**
1. Start run
2. Press pause button
3. Press "Sound Settings"
4. Music volume will be set to 0%

**Expected behavior**
Music volume not should change.

**Screenshots**

https://user-images.githubusercontent.com/36301121/175820354-957c0d51-49a2-4998-920d-baf465161c95.mp4

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A1
 - OS: Android 11
 - Version: 2.2.0

**Additional context**
This issue appears after 2.2.0.

**Comment by F121Live** [comment]
The game is probably not taking the correct value from the player's savedata, but if this is the case it should be defaulting to 100 instead...

Will investigate.

**Comment by F121Live** [comment]
Fixed in 2.2.1, will close this issue when the update is available to the public.
