### ISSUE TITLE
Just installed this with my jailbroken iOS 15.5 phone. Apparently it needs an update???

### ISSUE THREAD

**Issue by BeastMode4TM** [RunnersRevival/revival_issues#51]
I installed the game from the official website, then I attempted to open the game, and it showed me the following message (shown in attached screenshot): 
![DB5002F9-A07B-4036-87A1-E2BEEB4D2DEC](https://user-images.githubusercontent.com/105402464/211422401-a634d3cc-9991-4cf7-897a-8138f2955e82.png)

**Expected behavior**
I expected the game to launch lol

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus (jailbroken)
 - OS: iOS 15.5
 - Version: 2.2.3

**Comment by F121Live** [comment]
Follow the installation guide for Altstore in our website.

sonicrunners.com/#/altstore

**Comment by F121Live** [comment]
Closed, user is not installing correctly.
Not a real issue.
