### ISSUE TITLE
Un error de traduccion 

### ISSUE THREAD

**Issue by Abrahamelxd2021** [RunnersRevival/revival_issues#52]
**Describe the bug**
Estaba jugando a este juego cuando de la nada me encuentro con este error de traduccion 

**Expected behavior**
Jugando una partida normal y de repente me sale como una falta de traduccion al español.

**Screenshots or videos**
![Screenshot_20230210-173058](https://user-images.githubusercontent.com/104541078/218218407-bb5b3647-515c-4ca3-917e-26386d059bde.png)

**Smartphone (please complete the following information):**
 - Device: Compumax
 - OS: Android 11
 - Version: 2.2.3

.

**Comment by F121Live** [comment]
Please, only report issues in English.
