### ISSUE TITLE
Jackpot ring count drops to 1 after being obtained a single time

### ISSUE THREAD

**Issue by Delfite** [RunnersRevival/revival_issues#53]
### **Describe the bug**
I was playing some Sonic Runners Revival today and managed to get a jackpot twice in the same day from the item roulette. What I noticed though was that on the second time I won the jackpot the ring count was set to 1 for some reason. I thought it was a bug and decided to report it like the good little bug reporter I am.

### **How to Reproduce**
1. Go to the Item Roulette
2. Rank up twice to gain access to the Jackpot
3. Win the Jackpot Twice (consecutive wins aren't required)

### **What should've happened**
I expected the Jackpot's ring count to AT LEAST have been 185k like it was on my first win.

### **What actually happened**
The Jackpot's ring count was set to 1 when it most likely shouldn't have been. Bruh moment 💀

### **Screenshots or videos**
None. Explanation below.

### **Smartphone (please complete the following information):**
 - Device: Samsung S10+
 - OS: Android 12
 - Game Version: 2.2.3

### **Additional context**
The app I use to get screenshots of mobile games doesn't seem to work with sideloaded apps as far as I can tell but all you need to know is that it looked EXTREMELY cursed when I first saw it 😆

**Comment by FairPlay137** [comment]
This is expected behavior. You can only get the full jackpot once per day.

**Comment by Delfite** [comment]
Well that sucks. Thanks for telling me anyways.
