### ISSUE TITLE
Having a booster item already checked uses extra rings

### ISSUE THREAD

**Issue by ETheHedgehog** [RunnersRevival/revival_issues#58]
**Describe the bug**
After completing a run using a booster item, if you go to start a run again, it will deduct the rings for that item twice, and unchecking the item only returns 1x the item rings resulting in losing 1x the item rings forever.

**To Reproduce**
1. Start a run with a booster item
2. Finish the run
3. Go to start another run
4. Rings will get deducted twice

**Expected behavior**
Rings should be deducted once and unchecking the booster should return you to your original amount

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9T
 - OS: Android 11
 - Version: 2.2.3

**Comment by FairPlay137** [comment]
The server has no way of knowing what items you used during a run, and will always consume the item upon starting a run. This behavior was present in the original game and will not be changed.
