### ISSUE TITLE
After you change music volume during powerup wich changes BGM, stage music will play alongwise with powerup music

### ISSUE THREAD

**Issue by Ceotom** [RunnersRevival/revival_issues#6]
**Describe the bug**
After you change music volume in "Sound Settings" in pause menu and when you have powerup wich changes BGM, stage music will play alongwise with powerup music.

**To Reproduce**
1. Start run
2. Pickup Invincibility or Wisp
3. Press pause button
4. Open "Sound Settings" 
5. Change music volume
6. Return into game
7. Enjoy great mashup created by game

**Expected behavior**
Stage music not should play after such operations.

**Screenshots**

https://user-images.githubusercontent.com/36301121/175821003-e83c342a-8bb4-4b3f-905a-928670cae1a9.mp4

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A1
 - OS: Android 10, Android 11
 - Version: 2.1.1 - 2.2.0

**Additional context**
Video of this issue in 2.1.1 for reference:

https://user-images.githubusercontent.com/36301121/175821081-ee56e204-950c-4ab2-acfe-d91803f2187c.mp4

**Comment by F121Live** [comment]
Fixed in 2.2.1, will close this issue when the update is available to the public.
