### ISSUE TITLE
OP is labeled as inappropriate or invalid words, which disallows me to use my proper username.

### ISSUE THREAD

**Issue by gabeisop** [RunnersRevival/revival_issues#64]
**Describe the bug**
"OP" is labeled as inappropriate or invalid words.

**To Reproduce**
1. Change username.
2. Type in ANY word that has "OP" in it.
3. Click "OK"

**Expected behavior**
Should've been able to have my username as is, and not have to set it as "Hookthegreat" for the time being.

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.
![image](https://github.com/RunnersRevival/revival_issues/assets/24993070/77d08ec9-60ad-4930-a11e-a920ffab37a1)
![image](https://github.com/RunnersRevival/revival_issues/assets/24993070/8e3963be-1ffb-44a4-bc9b-44d3ccc5ad19)

**Smartphone (please complete the following information):**
 - Device: Laptop, Bluestacks.
 - OS:Bluestacks, unspecified android version.
 - Version: [e.g. 2.2.0] 2.2.3.

**Additional context**
No other context.

**Comment by FairPlay137** [comment]
This is a remnant of the original game, which did not allow names which could be seen as impersonation of staff. (The term "OP" can refer to a server operator)

**Comment by gabeisop** [comment]
Ah, that's fun.

**Comment by Ramen2X** [comment]
Going through some issues now; while offering a fix for this is quite tricky, I can manually correct your name for you if you provide your game ID (10-digit number in the top left corner of the title screen).

**Comment by gabeisop** [comment]
This is an issue i'm not quite worried about anymore. Thank you, though!
