### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by DaBoiCJ6241** [RunnersRevival/revival_issues#66]
**To Reproduce**
1. Make a outrun server
2. Change the URLS
3. Open the game
4. Stuck on connect.

**Expected behavior**
The game has to load the tutorial level.

**Smartphone (please complete the following information):**
 - Device: Samsung S21+
 - OS: Android 13
 - Version: latest

**Comment by FairPlay137** [comment]
Are you using Sonic Runners 2.0.3 as your game version?

**Comment by DaBoiCJ6241** [comment]
I will try it. How can i get the files for the assets?
