### ISSUE TITLE
Loading screen text for chapter 031-1 spoils story

### ISSUE THREAD

**Issue by emperortoehoe** [RunnersRevival/revival_issues#68]
**Describe the bug**
In chapter 031-1, the splash text that displays while loading implies the Master Emerald has been shattered, when that has not happened in the story(yet)

**To Reproduce**
1. Go to story mode chapter 031-1
2. Choose to play the level and wait for the loading screen
3. Look at the text

**Expected behavior**
A description that doesn’t spoil the story

**Screenshots or videos**
I already advanced to chapter 031-2 before deciding to report and am no longer able to provide a screenshot

**Smartphone (please complete the following information):**
 - Device: IPhone 12 Pro Max
 - OS: IOS 15.5
 - Version: 2.2.3t

**Comment by FairPlay137** [comment]
Quirk is present in original game. Won't fix.
