### ISSUE TITLE
Data Transfer Issue

### ISSUE THREAD

**Issue by ManyXFaces** [RunnersRevival/revival_issues#76]
**Describe the bug**
So it's almost been a year since the last time I played Revival on my android. And just today I got the game on my iPhone that I have been using for a while. I haven't progress further than the title screen because I know I can transfer my old account. When I tried putting my Transfer ID and Password it said it was incorrect even thought I have a screenshot of my game info a year ago in case I played the game again.

**Expected behavior**
I want to have my old account back with all of my characters unlocked so I don't have to start all over

I don't know if I should post the screenshot because it contains My ID, Transfer ID and Password and idk if this report is public.

 - Device: iPhone 14 Plus
  - OS: iOS 17.2.1
 - Game Version: 2.2.3

**Additional context**
If needed I can provide the screenshot through discord dm to not leak my game info

**Comment by Ramen2X** [comment]
I can look into this for you. What is your old account's ID? You do not need to provide further details than that.

**Comment by ManyXFaces** [comment]
> I can look into this for you. What is your old account's ID? You do not need to provide further details than that.

It is 205 399 1382 Hopefully there’s no issue with me moving the account since I am using a different device.

**Comment by Ramen2X** [comment]
Alright, got it. Fortunately, your account is still in our database and hasn't been removed for inactivity. What's your new ID? I can initiate a manual transfer for you.

**Comment by ManyXFaces** [comment]
Okay I quickly got passed the tutorial and my new ID is 276 092 6873

**Comment by Ramen2X** [comment]
Alright, I've completed the transfer. You should be able to access your old account data upon restarting the game.

**Comment by ManyXFaces** [comment]
Yea I got everything back. Thank you so much and have a nice day!

**Comment by Ramen2X** [comment]
You too, glad everything worked out.
