### ISSUE TITLE
Attempting to play Event Stage after playing Story Mode starts a Story Mode run

### ISSUE THREAD

**Issue by yeongy** [RunnersRevival/revival_issues#8]
**Describe the bug**
trying to play the event mode but puts me in story mode run

**To Reproduce**
play story mode
then play event mode (banner)
get put intop a story mode run instead of event despite clicking banner

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: galaxy s7
 - OS: android
 - Version [e.g. 2.2.0]

**Additional context**

**Comment by JKouga** [comment]
If you can, could you please record a video on the bug?

**Comment by yeongy** [comment]
[https://streamable.com/kgk98y](url)

**Comment by yeongy** [comment]
https://streamable.com/kgk98y

**Comment by Ramen2X** [comment]
This issue has been fixed internally and is waiting on a public release.

**Comment by F121Live** [comment]
Solved in 2.2.1.
