### ISSUE TITLE
Emulator issue with 2.2.4 update

### ISSUE THREAD

**Issue by RabbitSlime** [RunnersRevival/revival_issues#83]
**Describe the bug**
After updating Sonic Runners to 2.2.4 on an android emulator (BlueStacks), game refuses to connect _despite my PC having internet access_. Same result on running the app on another instance of Nougat 32 bit or a fresh instance of Pie 64 bit.

**To Reproduce**
1. Run an android emulator (BlueStacks or any other emulator)
2. Choose any OS available (mine was Nougat 32 bit, tested it on Pie 64 bit)
3. Install Sonic Runners on the emulator
4. Sonic Runners refuses to connect once opened

**Expected behavior**
I was expecting the game to handle the update properly and proceed to opening the game.

**Screenshots or videos**
![Screenshot_2024 01 10_21 07 47 846](https://github.com/RunnersRevival/revival_issues/assets/97825768/dd9871bb-c1c0-4113-84fe-24662d6688ed)

**Device specifications (please fill out the following information):**
 - Device: Samsung Galaxy S20+
 - OS: Nougat 32 bit and Pie 64 bit
 - Game Version: 2.2.4

**Additional context**
The game just basically refuses to connect, that's it. I do have my account tied to my phone as well. I normally use the phone to play the game for it's daily bounties when I'm out of town.

**Comment by Ceotom** [comment]
After testing i'm found this is because of standard assets (non-t). 
If version number says 2.2.4 rather than 2.2.4t this is it

Steps to reproduce if you have HD assets:
1. Run game and go to settings -> streamlined mode -> and enable Reduce image quality
2. Do not start download and close the game (important, if you don't restart game will run fine)
3. Run the game and try to login

**Comment by Ramen2X** [comment]
While BlueStacks is not officially supported or tested, I'll still try my best to help out here. Are you getting a connection failure immediately upon clicking the screen to start, or is it failing during loading?

**Comment by Ceotom** [comment]
This error occurs immediately after you touching screen to start.

**Comment by Ramen2X** [comment]
@Ceotom Thanks for the tip! Issue should now be resolved.

**Comment by RabbitSlime** [comment]
I'm actually stuck at the main menu with it's version saying as 2.2.4. It's not 2.2.4t; even with a fresh instance, the game simply refuses to connect. There's also a delay on when it shows the error message after attempting to connect.

**Comment by Ramen2X** [comment]
Clear cache and try again now.

**Comment by RabbitSlime** [comment]
There's another issue that comes up after the game refreshes to the title screen, as soon as you click play (or touch the screen) The connecting bar at the bottom right shows up for a moment before disappearing and the game kind of freezes. You can't press anything, no buttons but the music plays. Only an app reset fixes it.

**Comment by Ceotom** [comment]
> @Ceotom Thanks for the tip! Issue should now be resolved.

Nothing changed on my side, even after clearing cache. Pinged other people on Discord who has this issue.

**Comment by Ceotom** [comment]
![image](https://github.com/RunnersRevival/revival_issues/assets/36301121/2b902c04-f65b-42c3-929f-55febcc5b1c0)
No, issue still not fixed

**Comment by Ramen2X** [comment]
> ![image](https://github.com/RunnersRevival/revival_issues/assets/36301121/2b902c04-f65b-42c3-929f-55febcc5b1c0)
> 
> No, issue still not fixed 

Hmmm, that's odd. I'll investigate this.

**Comment by Ramen2X** [comment]
I'm sorry about that. There was a conflict with the Cloudflare caching of the assets. Issue should _actually_ be resolved now. @Ceotom @RabbitSlime

**Comment by Ceotom** [comment]
Yes, issue fixed for me

**Comment by RabbitSlime** [comment]
> I'm sorry about that. There was a conflict with the Cloudflare caching of the assets. Issue should _actually_ be resolved now. @Ceotom @RabbitSlime

Well, the issue is now resolved. The game is now downloading the new game assets.
